integrated_aruco_monitor:
  ros__parameters:
    # ArUco 검출 파라미터
    marker_length: 0.05
    camera_device: "/dev/video_cam"
    camera_width: 1200
    camera_height: 600
    camera_fps: 30
    
    # 필터 파라미터
    position_alpha: 0.7
    velocity_alpha: 0.3
    yaw_alpha: 0.6
    
    # 좌표 변환 파라미터
    src_points: [[-1.420, 0.097], [-1.528, -0.830], [0.459, 0.076], [0.410, -0.845]]
    dst_points: [[0.05, 0.05], [0.05, 0.95], [1.95, 0.05], [1.95, 0.95]]
    
    # TF 프레임 이름
    odom_frame: "odom"
    map_frame: "map"
    
    # GUI 업데이트 주기 (Hz)
    gui_update_rate: 30.0